CREATE TABLE `bk_users` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`openid` VARCHAR(50) NOT NULL,
	`nick_name` VARCHAR(50) NULL DEFAULT NULL,
	`real_name` VARCHAR(50) NULL DEFAULT NULL,
	`job_title` VARCHAR(500) NULL DEFAULT NULL,
	`job_desc` VARCHAR(500) NULL DEFAULT NULL,
	`job_location` VARCHAR(500) NULL DEFAULT NULL,
	`created_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX `Index 1` (`id`)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=5;


